"""KLS normal form for checking whether two stabilizer codes are LC-equivalent.

References for this algorithm:
- Andrey Boris Khesin, Jonathan Z. Lu, Peter W. Shor: Universal Graph Representation of Stabilizer Codes
- Andrey Boris Khesin, Jonathan Z. Lu, Peter W. Shor: Graphical quantum Clifford-encoder compilers from the ZX calculus
- Alexander Tianlin Hu, Andrey Boris Khesin: Improved Graph Formalism for Quantum Circuit Simulation
"""

from __future__ import annotations

from collections import deque

import numpy as np
import pyzx as zx

import ldpc.mod2.mod2_numpy as mod2

from ...core.stabilizer_code import StabilizerCode


class GSLC:
    """Graph state with local Clifford decorations (in encoder-respecting form), used for the KLS normal form."""

    def __init__(self) -> None:
        self.n = 0
        self.k = 0

        # each node identified with the index in the array, input nodes before output nodes
        # each node is represented by a local Clifford "word", which is an element of the group generated by S and H ("decoration" D_i), and a boolean z_i indicating whether there is an additional Z phase AT THE END or not.
        # eg:
        # I -> ([], False)
        # S -> (["S"], False)
        # Z -> ([], True),
        # S† = SZ -> (["S"], True),
        # H -> (["H"], False),
        # HS -> (["H", "S"], False),
        # HZ -> (["H"], True),
        # HS† = HSZ -> (["H", "S"], True)
        # SH -> (["S", "H"], False),
        # S†H -> (["S", "S", "S", "H"], False)
        self.vertices: list[tuple[list[str], bool]] = []
        self.edges: set[tuple[int, int]] = set()  # (u,v) with u < v
        self.adj: list[set[int]] = []  # optimization
        self._adj_edge_count = 0

    def _rebuild_adjacency(self) -> None:
        nr = self.n + self.k
        self.adj = [set() for _ in range(nr)]
        for u, v in self.edges:
            if 0 <= u < nr and 0 <= v < nr and u != v:
                self.adj[u].add(v)
                self.adj[v].add(u)
        self._adj_edge_count = len(self.edges)

    def _ensure_adjacency(self) -> None:
        nr = self.n + self.k
        if len(self.adj) != nr or self._adj_edge_count != len(self.edges):
            self._rebuild_adjacency()

    def set_edges(self, edges: set[tuple[int, int]]) -> None:
        self.edges = {(min(u, v), max(u, v)) for u, v in edges if u != v}
        self._rebuild_adjacency()

    def add_edge(self, u: int, v: int) -> None:
        if u == v:
            return
        self._ensure_adjacency()
        edge = (min(u, v), max(u, v))
        if edge not in self.edges:
            self.edges.add(edge)
            self.adj[u].add(v)
            self.adj[v].add(u)
            self._adj_edge_count = len(self.edges)

    def remove_edge(self, u: int, v: int) -> None:
        if u == v:
            return
        self._ensure_adjacency()
        edge = (min(u, v), max(u, v))
        if edge in self.edges:
            self.edges.remove(edge)
            self.adj[u].remove(v)
            self.adj[v].remove(u)
            self._adj_edge_count = len(self.edges)

    def get_input_output_adjacency(self) -> np.ndarray:
        self._ensure_adjacency()
        adj = np.zeros((self.k, self.n), dtype=bool)
        for edge in self.edges:
            u, v = edge
            if u < self.k and v >= self.k:
                adj[u, v - self.k] = True
        return adj

    def get_full_adjacency(self) -> np.ndarray:
        self._ensure_adjacency()
        adj = np.zeros((self.n + self.k, self.n + self.k), dtype=bool)
        for edge in self.edges:
            u, v = edge
            adj[u, v] = True
            adj[v, u] = True
        return adj

    def get_upper_adjacency_key(self) -> bytes:
        self._ensure_adjacency()
        nr = self.n + self.k
        upper = np.zeros(nr * (nr - 1) // 2, dtype=np.uint8)
        for u, v in self.edges:
            upper[u * (2 * nr - u - 1) // 2 + (v - u - 1)] = 1
        return np.packbits(upper).tobytes()

    def neighbors(self, v: int) -> list[int]:
        self._ensure_adjacency()
        return list(self.adj[v])

    def local_complementation(self, v: int) -> None:
        self._ensure_adjacency()
        neighbors = list(self.adj[v])
        for i in range(len(neighbors)):
            for j in range(i + 1, len(neighbors)):
                p = neighbors[i]
                q = neighbors[j]
                self.apply_cz_edge(p, q)

    def apply_cz_edge(self, u: int, v: int) -> None:  # toggle the edge (u,v)
        if u == v:
            return
        self._ensure_adjacency()
        edge = (min(u, v), max(u, v))
        if edge in self.edges:
            self.edges.remove(edge)
            self.adj[u].remove(v)
            self.adj[v].remove(u)
        else:
            self.edges.add(edge)
            self.adj[u].add(v)
            self.adj[v].add(u)
        self._adj_edge_count = len(self.edges)

    def copy(self) -> GSLC:
        self._ensure_adjacency()
        new_graph = GSLC()
        new_graph.n = self.n
        new_graph.k = self.k
        new_graph.vertices = [(deco.copy(), z) for deco, z in self.vertices]
        new_graph.edges = self.edges.copy()
        new_graph.adj = [neighbors.copy() for neighbors in self.adj]
        new_graph._adj_edge_count = self._adj_edge_count
        return new_graph

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, GSLC):
            return False
        return self.n == other.n and self.k == other.k and self.vertices == other.vertices and self.edges == other.edges


def _code_to_encoder_circuit(code) -> zx.Circuit:
    def _delete_first_row_and_qubit(tab: np.ndarray) -> np.ndarray:
        n = tab.shape[1] // 2
        return np.delete(np.delete(np.delete(tab, 0, axis=0), 0, axis=1), n - 1, axis=1)

    tableau = np.asarray(code.symplectic.copy(), dtype=np.uint8) & 1
    n = code.n
    k = code.k
    original_qubits = list(range(n))

    # Elimination gates are recorded in forward elimination order.
    elimination_gates: list[tuple[str, tuple[int, ...]]] = []
    while tableau.shape[0] > 0:
        cur_n = tableau.shape[1] // 2
        x0 = tableau[0, :cur_n]
        z0 = tableau[0, cur_n:]
        support = np.flatnonzero(x0 | z0)
        if len(support) == 0:
            raise ValueError("Encountered an identity stabilizer row.")

        # 1.) turn every non-identity Pauli in row 0 into Z
        # I = (0|0) --I---> I = (0|0)
        # X = (1|0) --H---> Z = (0|1)
        # Y = (1|1) --HS--> Z = (0|1)
        # Z = (0|1) --I---> Z = (0|1)
        for q in range(cur_n):
            x_q = bool(tableau[0, q])
            z_q = bool(tableau[0, cur_n + q])
            if x_q and z_q:
                # Y -> X under S
                tableau[:, q + cur_n] ^= tableau[:, q]
                tableau[:, [q, q + cur_n]] = tableau[:, [q + cur_n, q]]
                elimination_gates.append(("S", (original_qubits[q],)))
                elimination_gates.append(("H", (original_qubits[q],)))
            elif x_q and not z_q:
                # X -> Z under H
                tableau[:, [q, q + cur_n]] = tableau[:, [q + cur_n, q]]
                elimination_gates.append(("H", (original_qubits[q],)))

        # 2.) make the first qubit Z (pivot) CNOT(0 -> pivot)
        z_support = np.flatnonzero(tableau[0, cur_n:])

        if len(z_support) == 0:
            raise RuntimeError("Failed to convert stabilizer row to Z support.")
        pivot = int(z_support[0])

        if pivot != 0:
            tableau[:, pivot] ^= tableau[:, 0]
            tableau[:, cur_n + 0] ^= tableau[:, cur_n + pivot]
            elimination_gates.append(("CNOT", (original_qubits[0], original_qubits[pivot])))

        # 3.) clear all other Zs in row 0 using CNOT(q -> 0)
        # control: (x_c|z_c) --CNOT--> (  x_c  |z_c^z_t)
        # target : (x_t|z_t) --CNOT--> (x_t^x_c|  z_t  )
        for q in range(1, cur_n):
            if tableau[0, cur_n + q] == 1:
                tableau[:, 0] ^= tableau[:, q]
                tableau[:, cur_n + q] ^= tableau[:, cur_n + 0]

                elimination_gates.append(("CNOT", (original_qubits[q], original_qubits[0])))

        if (
            np.count_nonzero(tableau[0, :cur_n]) != 0
            or np.count_nonzero(tableau[0, cur_n:]) != 1
            or tableau[0, cur_n] != 1
        ):
            raise RuntimeError("Failed to isolate a stabilizer as a single Z.")

        # 4.) clear pivot column
        for r in range(1, tableau.shape[0]):
            if tableau[r, cur_n]:
                tableau[r] ^= tableau[0]
            if tableau[r, 0]:
                raise RuntimeError("A remaining row has X on the pivot qubit.")

        # 5.) remove stabilizer and qubit
        tableau = _delete_first_row_and_qubit(tableau)
        del original_qubits[0]

    # encoder = inverse elimination Cliffords
    circuit = zx.Circuit(n + k)
    circuit.initialize_qubits([True] * (n + k))
    # already prep with choi in mind
    for j in range(k):
        ref = j
        inp = k + (n - k) + j
        circuit.add_gate("HAD", ref)
        circuit.add_gate("CNOT", ref, inp)

    for name, qubits in reversed(elimination_gates):
        if name == "H":
            circuit.add_gate("HAD", qubits[0] + k)
        elif name == "S":
            # S† = Z phase 3π/2
            circuit.add_gate("ZPhase", qubits[0] + k, phase=3 / 2)
        elif name == "CNOT":
            circuit.add_gate("CNOT", qubits[0] + k, qubits[1] + k)

    return circuit


def _stab_state_to_graph_state(tableau: np.ndarray, old_n: int, old_k: int) -> GSLC:
    """Convert a stabilizer state into a graph state under local Clifford operations.
    Returns the adjacency matrix of the graph state."""
    n = tableau.shape[1] // 2
    local_clifords: list[list[str]] = [[] for _ in range(n)]

    def _rank(matrix: np.ndarray) -> int:
        if matrix.shape[0] == 0:
            return 0
        return mod2.rank(matrix)

    def _make_X_invertible(t: np.ndarray) -> np.ndarray:
        old_x_rank = _rank(t[:, :n])
        while old_x_rank < n:
            improved = False

            for q in range(n):
                if old_x_rank == n:
                    break

                best_rank = old_x_rank
                best_choice = (None, None)
                best_op = None

                x_col = t[:, q].copy()
                z_col = t[:, q + n].copy()

                for new_x, new_z, op in [
                    (x_col, z_col, []),
                    (z_col, x_col, ["H"]),
                    ((x_col + z_col) % 2, x_col, ["H", "S"]),
                ]:
                    t[:, q] = new_x
                    new_x_rank = _rank(t[:, :n])
                    if new_x_rank > best_rank:
                        best_rank = new_x_rank
                        best_choice = (new_x, new_z)
                        best_op = op

                if best_choice[0] is not None:
                    t[:, q] = best_choice[0]
                    t[:, q + n] = best_choice[1]
                    old_x_rank = best_rank
                    local_clifords[q] = best_op + local_clifords[q]
                    improved = True
                else:
                    t[:, q] = x_col
                    t[:, q + n] = z_col
                    local_clifords[q] = []

            if not improved:
                break

        return t

    def _extract_adjacency_matrix(tableau: np.ndarray) -> np.ndarray:
        """Extract the adjacency matrix from the stabilizer state."""

        def _rref_no_column_swaps(matrix: np.ndarray) -> tuple[np.ndarray, int]:
            n_rows, n_cols = matrix.shape
            pivot_row = 0
            for col in range(n_cols // 2):
                if pivot_row >= n_rows:
                    break

                tail = matrix[pivot_row:, col]
                pivot_offset = int(np.argmax(tail))

                if not tail[pivot_offset]:
                    continue

                pivot = pivot_row + pivot_offset

                if pivot != pivot_row:
                    matrix[[pivot_row, pivot], :] = matrix[[pivot, pivot_row], :]

                for r in range(n_rows):
                    if r != pivot_row and matrix[r, col]:
                        matrix[r, :] ^= matrix[pivot_row, :]
                pivot_row += 1

            return matrix, pivot_row

        rre, rank_x = _rref_no_column_swaps(tableau)

        if rank_x != n:
            raise ValueError("X part of the tableau is not full rank, something went wrong.")

        return rre[:, n:]

    def _remove_diagonal(tableau: np.ndarray) -> np.ndarray:
        """Basically apply S gate on all qubits to remove self-loops in the graph state."""
        for r in range(tableau.shape[0]):
            if tableau[r, r]:
                tableau[r, r] = 0
                local_clifords[r] = ["S"] + local_clifords[r]
        return tableau

    def _extract_decorations(deco: list[str]) -> tuple[list[str], bool]:
        z_bit = False
        if len(deco) > 1 and deco[-2:] == ["S", "S"]:
            return deco[:-2], True
        return deco, z_bit

    state = _make_X_invertible(tableau)
    gamma = _extract_adjacency_matrix(state)
    gamma = _remove_diagonal(gamma)

    if not np.array_equal(gamma, gamma.T):
        raise ValueError("Extracted adjacency matrix is not symmetric, something went wrong.")

    graph = GSLC()
    graph.n = old_n
    graph.k = old_k
    graph.vertices = [_extract_decorations(local_clifords[i]) for i in range(n)]
    edges = set()
    for i in range(n):
        for j in range(i + 1, n):
            if gamma[i, j]:
                edges.add((i, j))
    graph.set_edges(edges)

    return graph


def _code_to_graph(code) -> GSLC:
    """Convert the stabilizer code into a LC-equivalent graph state with local Clifford decorations on the vertices.

    1.) Convert the code into an encoder circuit using Gaussian elimination on the tableau.
    2.) Apply the Choi-Jamiołkowski isomorphism on the circuit, by applying the Bell-state |Φ⁺⟩ on the inputs and reference output qubits, which is the same as "bending the wires" in th ZX-calculus.
    3.) Apply the resulting circuit to the initial state |0⟩^(n+k) (stabilized by the tableau [0 | I]) to get the state tableau.
    4.) Convert the state tableau into a graph state under local Clifford operations (making X invertible, bringing the tableau into the form [I | A] and extracting the adjacency matrix A), constructing a GSLC object.
    """
    # 1.) Code -> Encoder Circuit
    circuit = _code_to_encoder_circuit(code)

    # 2.) Encoder Circuit -> State Tableau
    n = code.n + code.k
    initial_state = np.hstack([np.zeros((n, n), dtype=np.uint8), np.eye(n, dtype=np.uint8)])
    for gate in circuit.gates:
        if gate.name == "HAD":
            initial_state[:, [gate.target, n + gate.target]] = initial_state[:, [n + gate.target, gate.target]]
        elif gate.name == "ZPhase":
            if gate.phase == 1 / 2:
                initial_state[:, n + gate.target] ^= initial_state[:, gate.target]
            elif gate.phase == 1:
                pass  # Z has no effect on tableau
            elif gate.phase == 3 / 2:
                initial_state[:, n + gate.target] ^= initial_state[:, gate.target]
                # S† = SZ, but Z has no effect on tableau, so only apply S part to tableau
            else:
                raise ValueError(f"Unexpected Z phase {gate.phase} in encoder circuit.")
        elif gate.name == "CNOT":
            initial_state[:, gate.target] ^= initial_state[:, gate.control]
            initial_state[:, n + gate.control] ^= initial_state[:, n + gate.target]
        else:
            raise ValueError(f"Unexpected gate {gate.name} in encoder circuit.")

    # 3.) state tableau -> GSLC
    graph = _stab_state_to_graph_state(initial_state, code.n, code.k)

    return graph


def _hk_normal_form(graph: GSLC) -> None:
    """Requirements HK normal form:
    1.) graph like state (only Z nodes, one Z node per boundary, no inner Z edges, only H-edges between Z nodes)
    2.) Requirements on LC decorations:
        - only decorations I , S , H allowed (apart from additional Z phases)
        - if vertex has a H decoration, then it cannot have a neighbor with a smaller index
    """

    def _h_slide_down(g: GSLC, upper: int, lower: int) -> None:
        # (Eq. 13) H_upper |G> = H_lower Z_upper Z_lower prod_{p in A, q in B} CZ_{p,q} |G>
        # with A = N(upper) union {upper}, B = N(lower) union {lower}
        A = set(g.neighbors(upper)) | {upper}
        B = set(g.neighbors(lower)) | {lower}

        g.vertices[upper] = (g.vertices[upper][0][:-1], g.vertices[upper][1] ^ True)  # remove H, add Z

        if g.vertices[lower][0] and g.vertices[lower][0][-1] == "H":  # add H, add Z
            g.vertices[lower] = (g.vertices[lower][0][:-1], g.vertices[lower][1] ^ True)
        else:
            g.vertices[lower] = (g.vertices[lower][0] + ["H"], g.vertices[lower][1] ^ True)

        for p in A:
            for q in B:
                if p == q:
                    g.vertices[p] = (g.vertices[p][0], g.vertices[p][1] ^ True)  # add Z
                else:
                    g.apply_cz_edge(p, q)

    def _reduce_trailing_HS(g: GSLC, i: int) -> None:
        # (Eq. 12) H_i S_i |G> = S_i^3 prod_{p in N(i)} Z_p prod_{p,q in N(i)} CS_{p,q} |G>
        g.vertices[i] = (g.vertices[i][0][:-2] + ["S", "S", "S"], g.vertices[i][1])

        for j in g.neighbors(i):
            g.vertices[j][0].extend(["S", "S"])

        # as we handle every subset {p,q} of N(i) twice - as apply_cs_edge(p, q) and apply_cs_edge(q, p) - it effectively applies a CZ between them -> local complementation, with applying S to every neighbor of i (I THINK)
        #
        # for p in g.neighbors(i):
        #     for q in g.neighbors(i):
        #         if p == q:
        #            g.vertices[p][0] += ["S"]
        #         else:
        #             g.apply_cs_edge(p, q)

        for p in g.neighbors(i):
            g.vertices[p][0].append("S")

        g.local_complementation(i)

    def _reduce_solo_trailing_SH(g: GSLC, i: int) -> None:
        # (Eq. 11) S_i H_i |G> = H_i prod_{p,q in N(i)} CS_{p,q} |G>
        g.vertices[i] = (g.vertices[i][0][:-2] + ["H"], g.vertices[i][1])

        # as we handle every subset {p,q} of N(i) twice - as apply_cs_edge(p, q) and apply_cs_edge(q, p) - it effectively applies a CZ between them -> local complementation, with applying S to every neighbor of i (I THINK)
        #
        # for p in g.neighbors(i):
        #    for q in g.neighbors(i):
        #        if p == q:
        #            g.vertices[p][0] += ["S"]
        #        else:
        #            g.apply_cs_edge(p, q)

        for p in g.neighbors(i):
            g.vertices[p][0].append("S")

        g.local_complementation(i)

    def _reduce_shared_trailing_SH(g: GSLC, i: int, j: int) -> None:
        # (Eq. 11) H_i H_j|G> = Z_i Z_j prod_{p in A, q in B} CZ_{p,q} |G>
        # with A = N(i) union {i}, B = N(j) union {j}
        A = set(g.neighbors(i)) | {i}
        B = set(g.neighbors(j)) | {j}

        g.vertices[i] = (g.vertices[i][0][:-1] + ["S", "S"], g.vertices[i][1])
        g.vertices[j] = (g.vertices[j][0][:-1] + ["S", "S"], g.vertices[j][1])

        for p in A:
            for q in B:
                if p == q:
                    g.vertices[p][0].extend(["S", "S"])
                else:
                    g.apply_cz_edge(p, q)

    def _reduce_word(word: tuple[list[str], bool]) -> tuple[list[str], bool]:
        new_z_bit = word[1]
        deco = word[0]
        # remove identities and push Z back
        changed = True
        while changed:
            new_deco = []
            changed = False
            i = 0

            while i < len(deco):
                if i + 1 < len(deco):
                    a, b = deco[i], deco[i + 1]

                    if (a == "H" and b == "H") or (a == "Z" and b == "Z"):
                        changed = True
                        i += 2
                        continue
                    if a == "S" and b == "S":
                        changed = True
                        new_deco += ["Z"]
                        i += 2
                        continue
                    if a == "Z" and b == "S":
                        changed = True
                        new_deco += ["S", "Z"]
                        i += 2
                        continue
                new_deco.append(deco[i])
                i += 1

            deco = new_deco

        # remove Z at the end
        while deco and deco[-1] == "Z":
            deco = deco[:-1]
            new_z_bit ^= True

        # make valid decoration
        extended_deco = []
        for i in range(len(deco)):
            if deco[i] == "Z":
                extended_deco += ["S", "S"]
            else:
                extended_deco.append(deco[i])

        return extended_deco, new_z_bit

    n = graph.n + graph.k

    # 1.) reduce LC decorations to either I, S, or H (and potentially additional Z bit)
    changed = True
    while changed:
        changed = False

        for i in range(n):
            graph.vertices[i] = _reduce_word(graph.vertices[i])
            if len(graph.vertices[i][0]) < 2:
                continue
            if graph.vertices[i][-2:][0] == ["H", "S"]:
                _reduce_trailing_HS(graph, i)
                changed = True
                break
            if graph.vertices[i][-2:][0] == ["S", "H"]:
                h_neighbors = [j for j in graph.neighbors(i) if graph.vertices[j][0][-1:] == ["H"]]
                if len(h_neighbors) == 0:
                    _reduce_solo_trailing_SH(graph, i)
                else:
                    _reduce_shared_trailing_SH(graph, i, h_neighbors[0])
                changed = True
                break

    for i in range(n):
        deco, _ = graph.vertices[
            i
        ]  # should only be I, S, or H decorations (+ additional Z bits) left (aka I, Z, S, SZ = S†, H, HZ)
        if deco not in ([], ["S"], ["H"]):
            raise ValueError(f"After reduction of decorations: Expected only I, S, or H decorations, but got: {deco}.")

    # 2.) slides trailing H down
    for x in reversed(range(n)):
        while graph.vertices[x][0][-1:] == ["H"]:  # x has a trailing Hadamard
            low_neighbors = [v for v in graph.neighbors(x) if v < x]
            if len(low_neighbors) == 0:
                break

            y = min(low_neighbors)
            _h_slide_down(graph, x, y)

    for x in range(n):
        if graph.vertices[x][0] not in ([], ["H"], ["S"], ["S", "H"]):
            raise ValueError(
                f"After sliding down all H: Expected only I, S, H decorations, but got: {graph.vertices[x][0]}."
            )
    # now should only have decorations I , H, S, SH

    # 3.) cleanup SH decorations
    for i in range(n):
        if graph.vertices[i][0] == ["S", "H"]:  # apply Eq. 11
            graph.vertices[i] = (["H"], graph.vertices[i][1])
            for p in graph.neighbors(i):
                if graph.vertices[p][0] == []:
                    graph.vertices[p] = (["S"], graph.vertices[p][1])
                elif graph.vertices[p][0] == ["S"]:
                    graph.vertices[p] = ([], graph.vertices[p][1] ^ True)
                else:
                    raise ValueError(
                        f"Expected only I, S decorations in the neighborhood of a H-decorated vertex, but got: {graph.vertices[p][0]}"
                    )
            graph.local_complementation(i)

    for x in range(n):
        if graph.vertices[x][0] not in ([], ["H"], ["S"]):
            raise ValueError(
                f"After cleaning up SH: Expected only I, S, H decorations, but got: {graph.vertices[x][0]}."
            )


def _kls_normal_form(graph: GSLC) -> None:
    """Additional requirements KLS normal form:
    1.) input nodes have no non-I LC decoration, and no edges between input nodes
    2.) the input-output adjacency matrix is in RREF
    3.) the pivot columns of the input-output adjacency matrix have no non-I LC decorations, and no edges between pivot vertices
    """

    # 1.) set input vertices to have no decoration and no edges
    def _strip_input() -> None:
        for q in range(graph.k):
            graph.vertices[q] = ([], False)

        graph.set_edges({(u, v) for u, v in graph.edges if not (u < graph.k and v < graph.k)})

    _strip_input()

    # 2.) bring the IO-adjacency matrix into RREF
    adj = graph.get_input_output_adjacency()

    def _rref_no_column_swaps(matrix: np.ndarray) -> tuple[np.ndarray, dict[int, int]]:
        pivot_row = 0
        pivots = {}
        for c in range(graph.n):
            if pivot_row >= graph.k:
                break

            tail = matrix[pivot_row:, c]
            pivot_offset = int(np.argmax(tail))

            if not tail[pivot_offset]:
                continue

            pivots[pivot_row] = c + graph.k

            pivot = pivot_row + pivot_offset
            if pivot != pivot_row:
                matrix[[pivot_row, pivot]] = matrix[[pivot, pivot_row]]

            for r in range(graph.k):
                if r != pivot_row and matrix[r, c]:
                    matrix[r] ^= matrix[pivot_row]

            pivot_row += 1

        return matrix, pivots

    adj, pivots = _rref_no_column_swaps(adj)

    # 3.) set the IO-edges according to the new adjacency matrix (equivalent to applying the corresponding CNOT gates on the graph state and simplifying with bialgebra rule -> output-output edges and decorations not changed)
    def _set_io_edges(adj: np.ndarray) -> None:
        new_edges = set()
        for input in range(graph.k):
            for output in range(graph.n):
                if adj[input, output]:
                    new_edges.add((input, output + graph.k))

        for u, v in graph.edges:
            if u >= graph.k and v >= graph.k:
                new_edges.add((u, v))

        graph.set_edges(new_edges)

    _set_io_edges(adj)

    # 4.) remove pivot vertex decorations (apply local complementation)
    # |G> = prod_{p,q in N(i)} CS_{p,q} |G>
    def _add_S(word: tuple[list[str], bool]) -> tuple[list[str], bool]:
        new_z_bit = word[1]
        deco = word[0] + ["S"]

        while len(deco) >= 2:
            if deco[-2:] == ["S", "S"]:
                deco = deco[:-2]
                new_z_bit ^= True
            else:
                break

        return deco, new_z_bit

    for input, pivot in pivots.items():
        deco, z = graph.vertices[pivot]

        if "H" in deco:
            raise ValueError(
                f"Pivot {pivot} has an H decoration. Should have been pushed to a (lower numbered) input during HK normal form reduction."
            )

        if z:
            graph.vertices[pivot] = (deco + ["S", "S"], False)

        while "S" in graph.vertices[pivot][0] or graph.vertices[pivot][1]:
            neighbors = graph.neighbors(input)

            for neighbor in neighbors:
                graph.vertices[neighbor] = _add_S(graph.vertices[neighbor])

            graph.local_complementation(input)

    # 5.) remove pivot-pivot edges, basically apply Eq. 11 (but HZ on inputs can be removed)
    # |G> = H_i Z_i H_j Z_j prod_{p in A, q in B} CZ_{p,q} |G>
    # with A = N(i) union {i}, B = N(j) union {j}
    pivot_to_input = {pivot: input for input, pivot in pivots.items()}
    pivot_vertices = set(pivot_to_input)
    while True:
        pivot_edge = next(
            ((u, v) for u, v in graph.edges if u in pivot_vertices and v in pivot_vertices),
            None,
        )
        if pivot_edge is None:
            break

        u, v = pivot_edge
        i = pivot_to_input[u]
        j = pivot_to_input[v]

        A = {v for v in graph.neighbors(i) if v >= graph.k}
        B = {v for v in graph.neighbors(j) if v >= graph.k}

        for p in A:
            for q in B:
                if p == q:
                    graph.vertices[p] = (graph.vertices[p][0], graph.vertices[p][1] ^ True)  # add Z
                else:
                    graph.apply_cz_edge(p, q)

        for output in A | B:
            graph.remove_edge(i, output)
            graph.remove_edge(j, output)

        for output in B:
            graph.add_edge(i, output)

        for output in A:
            graph.add_edge(j, output)

        pivot_to_input[u], pivot_to_input[v] = j, i
        _strip_input()

    # 6.) swap the neighborhoods back via row operations, aka bring back into RREF
    adj = graph.get_input_output_adjacency()
    adj, _ = _rref_no_column_swaps(adj)
    _set_io_edges(adj)


def _traverse_lc_orbit(graph: GSLC, target: GSLC) -> bool:
    """Traverse LC orbit and re-canonicalize to KLS normal form at each step"""

    def _canonical_key(g: GSLC) -> tuple[int, int, bytes, tuple[tuple[tuple[str, ...], bool], ...]]:
        adj_key = g.get_upper_adjacency_key()
        vertex_key = tuple((tuple(word), z) for word, z in g.vertices)
        return (g.n, g.k, adj_key, vertex_key)

    start = graph.copy()
    seen = {_canonical_key(start)}
    queue = deque([start])

    while queue:
        current_graph: GSLC = queue.popleft()

        if current_graph == target:
            return True

        for q in range(graph.k, graph.n + graph.k):
            for gate in ["H", "S"]:
                new_graph = current_graph.copy()

                new_graph.vertices[q] = (new_graph.vertices[q][0] + [gate], new_graph.vertices[q][1])
                _hk_normal_form(new_graph)
                _kls_normal_form(new_graph)

                key = _canonical_key(new_graph)

                if key not in seen:
                    queue.append(new_graph)
                    seen.add(key)

    return False


def are_lceq_kls(code1: StabilizerCode, code2: StabilizerCode) -> bool:
    """Check if two stabilizer codes are LC-equivalent by traversing the LC orbit of one, renormalizing at each step and checking if the KLS form of the other one is found.

    For each code, the following is done:
    1.) Convert the stabilizer code into a graph-like state, aka a graph with local Clifford decorations on the vertices, using the Encoder Circuit and Choi.
    2.) Convert the graph-like state into HK normal form, while treating the input vertices as output vertices.
    3.) Convert the HK normal form into KLS normal form, treating the input vertices as inputs again.

    4.) Traverse the LC orbit of one resulting graph, renormalize and check if the other graph is found.

    Even tough we need to check the entire LC Orbit, with the KLS we at least remove the degrees of freedom that the logical basis choice adds for k > 1, which would add the ARBITRARY Clifford orbit on input/reference qubits.
    """
    graph1 = _code_to_graph(code1)
    _hk_normal_form(graph1)
    _kls_normal_form(graph1)

    graph2 = _code_to_graph(code2)
    _hk_normal_form(graph2)
    _kls_normal_form(graph2)

    return _traverse_lc_orbit(graph1, graph2)
